version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - team-time-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - team-time-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=team_time_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - team-time-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - team-time-network

volumes:
  postgres_data:

networks:
  team-time-network:
    driver: bridge
